-- EMERGENCY: Disable RLS on all tables to restore production
-- The backend uses raw pg connections where auth.uid() is NULL, breaking all policies

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE players DISABLE ROW LEVEL SECURITY;
ALTER TABLE holdings DISABLE ROW LEVEL SECURITY;
ALTER TABLE holdings_locks DISABLE ROW LEVEL SECURITY;
ALTER TABLE balance_locks DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE vesting DISABLE ROW LEVEL SECURITY;
ALTER TABLE vesting_splits DISABLE ROW LEVEL SECURITY;
ALTER TABLE vesting_claims DISABLE ROW LEVEL SECURITY;
ALTER TABLE vesting_presets DISABLE ROW LEVEL SECURITY;
ALTER TABLE contests DISABLE ROW LEVEL SECURITY;
ALTER TABLE contest_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE contest_lineups DISABLE ROW LEVEL SECURITY;
ALTER TABLE player_game_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE price_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_games DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_execution_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE portfolio_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE market_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_actions_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE premium_checkout_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE premium_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE premium_trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE whop_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE tweet_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE tweet_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE watchlists DISABLE ROW LEVEL SECURITY;
ALTER TABLE watch_list DISABLE ROW LEVEL SECURITY;

SELECT 'RLS DISABLED on all tables - production restored' AS status;
